export interface Feed {
  name: string;
  author?: string;
  url: string;
  type: "podcast" | "newsletter";
  emoji: string;
  tags: string[];
}

export const FEEDS: Feed[] = [
  // ── Podcasts ──────────────────────────────────────────────────────────────
  {
    name: "Acquired",
    author: "Ben Gilbert & David Rosenthal",
    url: "https://feeds.transistor.fm/acquired",
    type: "podcast",
    emoji: "🎙",
    tags: ["VC", "Finance", "Tech"],
  },
  {
    name: "Business Breakdowns",
    author: "Colossus",
    url: "https://feeds.megaphone.fm/breakdowns",
    type: "podcast",
    emoji: "🎙",
    tags: ["VC", "Finance"],
  },
  {
    name: "Invest Like the Best",
    author: "Patrick O'Shaughnessy",
    url: "https://feeds.megaphone.fm/investlikethebest",
    type: "podcast",
    emoji: "🎙",
    tags: ["VC", "IB", "Finance"],
  },
  {
    name: "In Depth",
    author: "First Round Capital",
    url: "https://feeds.simplecast.com/Gb7vhP5p",
    type: "podcast",
    emoji: "🎙",
    tags: ["VC", "Startups"],
  },
  {
    name: "No Priors",
    author: "Elad Gil & Sarah Guo",
    url: "https://feeds.megaphone.fm/nopriors",
    type: "podcast",
    emoji: "🎙",
    tags: ["VC", "AI", "Tech"],
  },
  {
    name: "Training Data",
    author: "Sequoia Capital",
    url: "https://feeds.megaphone.fm/trainingdata",
    type: "podcast",
    emoji: "🎙",
    tags: ["VC", "AI", "Tech"],
  },
  {
    name: "The a16z Podcast",
    author: "Andreessen Horowitz",
    url: "https://feeds.simplecast.com/JGE3yC0V",
    type: "podcast",
    emoji: "🎙",
    tags: ["VC", "Tech", "Startups"],
  },
  {
    name: "Lenny's Podcast",
    author: "Lenny Rachitsky",
    url: "https://api.substack.com/feed/podcast/10845.rss",
    type: "podcast",
    emoji: "🎙",
    tags: ["Tech", "Startups", "Growth"],
  },
  {
    name: "Unsolicited Feedback",
    author: "Brian Balfour & Fareed Mosavat",
    url: "https://feeds.megaphone.fm/unsolicitedfeedback",
    type: "podcast",
    emoji: "🎙",
    tags: ["Tech", "Startups", "Growth"],
  },
  {
    name: "Unsupervised Learning",
    author: "Jacob Effron",
    url: "https://omny.fm/shows/unsupervised-learning/playlists/podcast.rss",
    type: "podcast",
    emoji: "🎙",
    tags: ["AI", "Tech"],
  },
  {
    name: "The OpenAI Podcast",
    author: "OpenAI",
    url: "https://feeds.acast.com/public/shows/openai-podcast",
    type: "podcast",
    emoji: "🎙",
    tags: ["AI", "Tech"],
  },
  {
    name: "The Tim Ferriss Show",
    author: "Tim Ferriss",
    url: "https://rss.art19.com/tim-ferriss-show",
    type: "podcast",
    emoji: "🎙",
    tags: ["Growth", "Tech"],
  },
  {
    name: "Dwarkesh Podcast",
    author: "Dwarkesh Patel",
    url: "https://api.substack.com/feed/podcast/69345.rss",
    type: "podcast",
    emoji: "🎙",
    tags: ["AI", "Tech"],
  },
  {
    name: "Stepchange",
    author: "Ben Eidelson & Anay Shah",
    url: "https://stepchangeshow.substack.com/feed",
    type: "podcast",
    emoji: "🎙",
    tags: ["Tech", "Startups"],
  },

  // ── Newsletters ───────────────────────────────────────────────────────────
  {
    name: "First Round Review",
    author: "First Round Capital",
    url: "https://review.firstround.com/feed",
    type: "newsletter",
    emoji: "📝",
    tags: ["VC", "Startups"],
  },
  {
    name: "Not Boring",
    author: "Packy McCormick",
    url: "https://notboring.substack.com/feed",
    type: "newsletter",
    emoji: "📝",
    tags: ["Finance", "Tech", "Startups"],
  },
  {
    name: "Next Big Thing",
    author: "Nikhil Basu Trivedi",
    url: "https://nbt.substack.com/feed",
    type: "newsletter",
    emoji: "📝",
    tags: ["VC", "Startups"],
  },
  {
    name: "a16z speedrun",
    author: "Andreessen Horowitz",
    url: "https://speedrun.substack.com/feed",
    type: "newsletter",
    emoji: "📝",
    tags: ["VC", "Startups"],
  },
  {
    name: "Digital Native",
    author: "Rex Woodbury",
    url: "https://digitalnative.substack.com/feed",
    type: "newsletter",
    emoji: "📝",
    tags: ["Tech", "Startups"],
  },
  {
    name: "Newcomer",
    author: "Eric Newcomer",
    url: "https://newcomer.co/feed",
    type: "newsletter",
    emoji: "📝",
    tags: ["VC", "Tech"],
  },
  {
    name: "Interconnects AI",
    author: "Nathan Lambert",
    url: "https://www.interconnects.ai/feed",
    type: "newsletter",
    emoji: "📝",
    tags: ["AI", "Tech"],
  },
  {
    name: "Refactoring",
    author: "Lenny Rachitsky",
    url: "https://refactoring.substack.com/feed",
    type: "newsletter",
    emoji: "📝",
    tags: ["Tech", "Growth"],
  },
  {
    name: "Polymath Investor",
    url: "https://www.polymathinvestor.com/feed",
    type: "newsletter",
    emoji: "📝",
    tags: ["Finance", "VC"],
  },
  {
    name: "Tiger Feathers",
    url: "https://tigerfeathers.substack.com/feed",
    type: "newsletter",
    emoji: "📝",
    tags: ["India", "Tech"],
  },
  {
    name: "The India Notes",
    url: "https://newsletter.theindianotes.com/feed",
    type: "newsletter",
    emoji: "📝",
    tags: ["India", "Finance"],
  },
  {
    name: "The Indian Pivot",
    url: "https://theindianpivot.substack.com/feed",
    type: "newsletter",
    emoji: "📝",
    tags: ["India", "Startups"],
  },
  {
    name: "kuwi.news",
    url: "https://www.kuwi.news/feed",
    type: "newsletter",
    emoji: "📝",
    tags: ["India"],
  },
  {
    name: "Aftermarket Report",
    author: "Zerodha",
    url: "https://aftermarketreport.zerodha.com/feed",
    type: "newsletter",
    emoji: "📝",
    tags: ["Finance", "India"],
  },
  {
    name: "Zerodha Varsity",
    author: "Zerodha",
    url: "https://zerodhavarsity.substack.com/feed",
    type: "newsletter",
    emoji: "📝",
    tags: ["Finance", "India"],
  },
  {
    name: "George Mack",
    author: "George Mack",
    url: "https://www.george-mack.com/feed",
    type: "newsletter",
    emoji: "📝",
    tags: ["Growth"],
  },
  {
    name: "Technically",
    url: "https://read.technically.dev/feed",
    type: "newsletter",
    emoji: "📝",
    tags: ["Tech"],
  },
  {
    name: "Sanjeev Srivastav",
    author: "Sanjeev Srivastav",
    url: "https://sanjeevsrivastav.substack.com/feed",
    type: "newsletter",
    emoji: "📝",
    tags: ["India", "Startups"],
  },
];
